#### This script is to provide a further filtering (mostly on doublets) and make new QC plots
args = commandArgs(trailingOnly=TRUE)
dir = args[1] 
v_ADT=as.logical(args[2]) # TRUE: ADT assay; FALSE: no ADT assay 
v_VDJ=as.logical(args[3]) # TRUE: VDJ assay; FALSE: no VDJ assay 

.libPaths("/usr/local/lib/R/library")
library(Polychrome) 
library(Seurat)
library(tibble)
library(ggplot2)
library(dplyr)
library(cowplot)
#library(UpSetR)
#library(tidyverse)


# setup dir, path to smaple list, name of singleR database to plot
if (Sys.info()['sysname'] == "Windows"){
  dir <- 'M:/dept/Dept_BBSR/Projects/Monteiro_Alvaro/3900_Monteiro_10x_2022/' # project dir
  
}


# setup dir, path to smaple list, name of singleR database to plot

work_dir <- paste0(dir, "/work") # work dir
output_folder<- paste(work_dir,'QC/',sep="/") # define output dir
#input_folder<-"/iCel3_iFtu200_xMT10log10GPU0.8/" # define folder names of input .rds data
sample_list<-read.delim(paste(work_dir,"sample.list",sep="/"),header=F) # read in sample name
singleR_type<-"hpca.main" # define name of singleR database
large_sample_cutoff<-12000 # define samples with large number of cells

tmp_size =ifelse(dim(sample_list)[1] > 10, 12 + dim(sample_list)[1]*0.5, 12)

# allow png
# R/4.0.2 on old cluster may have issue with generating png 
options(bitmapType='cairo')



# load the metadata_sum generated by 2_merged_QC_png.R
load(paste0(output_folder,'/metadata_sum.Rdata'))
load( paste0(output_folder,'/color_book.Rdata'))
source(paste0(dir,'/scripts/scRNA_beta/S_QC_plots.R'))


# customize the filter criteria
# doublet_pos_methods < 2: remove called by >=2 callers
# log10GenesPerUMI_RNA > 0.8: remove log10GenesPerUMI_RNA<=0.8
# log10GenesPerUMI_RNA > 0.8: remove log10GenesPerUMI_RNA<=0.8
# nFeature_RNA >200: remove nFeature_RNA<=200
# percent.mt<15: remove percent.mt>=15

metadata_sum_new <- metadata_sum %>%
  filter(doublet_pos_methods < 2 & log10GenesPerUMI_RNA > 0.8 & nFeature_RNA >200 & percent.mt<15)

count<-cbind(table(metadata_sum$old.ident),table(metadata_sum_new$orig.ident))
colnames(count)<-c("raw","filtered")
write.csv(count,paste0(output_folder,"/cellcount.csv"))

##scRNA qc
sc_QC_plots <- plot_sc_QC(metadata_sum_new, 
                          myUMIcutoff = 200,
                          myGenecutoff = 200,
                          mymitoratiocut = 15,
                          mylog10GenesPerUMIcut = 0.8,
                          sample_color,
                          cell_type_var = singleR_type)

for(i in 1:length(sc_QC_plots)){
  png(paste0(output_folder,names(sc_QC_plots)[i],".new_filtered.png"), width =tmp_size, height =tmp_size,res=300,units = "in")
  print(sc_QC_plots[[i]])
  dev.off()
}


##scADT qc

## ADT QC plots
if(v_ADT){
ADT_QC_plots <- plot_ADT_QC(metadata_sum_new, 
                            sample_color)

for(i in 1:length(ADT_QC_plots)){
  png(paste0(output_folder,names(ADT_QC_plots)[i],".new_filtered.png"), width =tmp_size, height =tmp_size,res=300,units = "in")
  print(ADT_QC_plots[[i]])
  dev.off()
}

}

## doublet
double_method_count_plots <- plot_doublet_method_count(doublet_df = metadata_sum_new,
                                                       doublet_color = doublet_method_color,
                                                       myUMIcutoff = 200,
                                                       myGenecutoff = 200,
                                                       cell_type_var =singleR_type, 
                                                       cluster_var = NULL, 
                                                       method_n_var = 'doublet_pos_methods',
                                                       my_ncol = 3)


# the width and height need to be modified based on the sample size and my_ncol
for(i in 1:length(double_method_count_plots)){
  png(paste0(output_folder,names(double_method_count_plots)[i],".new_filtered.png"), width =tmp_size, height =tmp_size,res=300,units = "in")
  print(double_method_count_plots[[i]])
  dev.off()
}

